name: Cypress Tests

on:
 push:
  branches: "*"
 pull_request:
  branches: "*"

jobs:
 install:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   # Install Yarn dependencies, cache them correctly
   # and run all Cypress tests
   - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./yasmina-landing-page
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
