name: Cypress Tests

on:
 push:
  branches: "*"
 pull_request:
  branches: "*"

jobs:
 wait:
  runs-on: ubuntu-20.04
  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Cypress tests
     uses: ./
     with:
      # wait for the URL to respond
      # using the default parameter
      working-directory: examples/wait-on
      start: npm start
      wait-on: "http://localhost:3050"
