name: Cypress Tests

on:
 push:
  branches: "*"
 pull_request:
  branches: "*"

jobs:
 cypress-run:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2.4.2
   - name: Cypress.io
     uses: cypress-io/github-action@v2.9.7
     with:
      start: yarn start
